### ISSUE TITLE
[Compatibility] qwen-tts 0.1.1 requires transformers==4.57.3 but qwen3_tts needs transformers >= 5.x

### ISSUE THREAD

**Issue by lyangfan** [QwenLM/Qwen3-TTS#237]
### Description

qwen-tts Python package (0.1.1) has a dependency conflict:
- It requires `transformers==4.57.3` (hardcoded in setup.py)
- But qwen3_tts architecture needs `transformers >= 5.x` for `check_model_inputs` function

This makes it impossible to use qwen-tts package with the latest transformers that supports qwen3_tts architecture.

### To Reproduce

```bash
# Create conda environment
conda create -n qwen3-tts python=3.12 -y
conda activate qwen3-tts

# Install qwen-tts
pip install qwen-tts

# Try to import
python3 -c "from qwen_tts import Qwen3TTSModel"
```

Error:
```
ImportError: cannot import name 'check_model_inputs' from 'transformers.utils.generic'
```

### Expected behavior

qwen-tts should support transformers >= 5.x or provide a compatibility layer for the `check_model_inputs` function.

### Environment
- qwen-tts: 0.1.1
- transformers: 4.57.3 (installed by qwen-tts) vs 5.x (needed by qwen3_tts)
- Python: 3.12
- OS: macOS 15.3 (Apple Silicon M5)

### Additional context

The issue is that `qwen_tts/core/tokenizer_12hz/modeling_qwen3_tts_tokenizer_v2.py` line 42 imports:
```python
from transformers.utils.generic import check_model_inputs
```

This function does not exist in transformers 4.57.3, but exists in transformers 5.x.

### Suggested Fix

1. Update setup.py to allow transformers >= 5.0.0
2. Or provide a shim/compatibility layer for `check_model_inputs` function
3. Or update qwen-tts to use the correct transformers version

Thank you for your work on this project!

**Comment by Athwale** [comment]
transformers 5.3.0
ImportError: cannot import name 'check_model_inputs' from 'transformers.utils.generic
Looks like it is not fixing it. Python 3.12 as well.
This will work only with pip install --force-reinstall -v "transformers==5.1.0"
But then you get this issue 'Qwen3TTSTalkerConfig' object has no attribute 'pad_token_id'
pip install --force-reinstall -v "transformers==4.57.3" is working now.

**Comment by jdc4429** [comment]
See my messages under https://github.com/QwenLM/Qwen3-TTS/issues/239

Grab the file: [modeling_qwen3_tts_tokenizer_v2-FIXED.py](https://github.com/user-attachments/files/26160937/modeling_qwen3_tts_tokenizer_v2-FIXED.py)

check_model_inputs which does not actually exist is causing the issue and is not actually used.
By editing this out, it works.

Rename FIXED version and copy over existing file to fix the issue or manually edit like so:
File located under: C:\Qwen3-TTS\qwen_tts\core\tokenizer_12hz

Comment out these 2 lines:
# from transformers.utils.generic import check_model_inputs  # Removed - function doesn't exist
#    @check_model_inputs()  # Removed - function doesn't exist

Qwen3-TTS does not need transformers 5.x... Version 4.57.3 works fine... At least for the best version with no API and v2ProPlus
You should be using an environment under python 3.10, not 3.12 as this can cause issues.

**Comment by kgpabhi** [comment]
> See my messages under [#239](https://github.com/QwenLM/Qwen3-TTS/issues/239)
> 
> Grab the file: [modeling_qwen3_tts_tokenizer_v2-FIXED.py](https://github.com/user-attachments/files/26160937/modeling_qwen3_tts_tokenizer_v2-FIXED.py)
> 
> check_model_inputs which does not actually exist is causing the issue and is not actually used. By editing this out, it works.
> 
> Rename FIXED version and copy over existing file to fix the issue or manually edit like so: File located under: C:\Qwen3-TTS\qwen_tts\core\tokenizer_12hz
> 
> Comment out these 2 lines:
> # from transformers.utils.generic import check_model_inputs # Removed - function doesn't exist
> # @check_model_inputs() # Removed - function doesn't exist
> 
> Qwen3-TTS does not need transformers 5.x... Version 4.57.3 works fine... At least for the best version with no API and v2ProPlus You should be using an environment under python 3.10, not 3.12 as this can cause issues.

Tried your method for using Qwen TTS Voice clone in comfyUI by using your file and updating transformers to 5.3.0. The check model inputs error during comfy launch is solved but on using Qwen TTS clone node it throws a pad_token_id error.
'Qwen3TTSTalkerConfig' object has no attribute 'pad_token_id'

similar to: https://github.com/flybirdxx/ComfyUI-Qwen-TTS/issues/21

**Comment by jdc4429** [comment]
Is it an error or a warning?

I only fixed everything late last night, you may not have a good working
version.  I think I fixed everything now.
Try installing from scratch from the latest version.  I thought I could
combine them on the same conda env but found transformers 4.50 was max for
one and the other requires 4.57.3 so I had to separate to two conda devs.

Don't update to transformers 5.3.0.. The versions specified should work
fine.  Just make sure you create from scratch in a conda env (Qwen3) -
Conda envs are case sensitive.

**Comment by kgpabhi** [comment]
> Is it an error or a warning?
> 
> I only fixed everything late last night, you may not have a good working
> version.  I think I fixed everything now.
> Try installing from scratch from the latest version.  I thought I could
> combine them on the same conda env but found transformers 4.50 was max for
> one and the other requires 4.57.3 so I had to separate to two conda devs.
> 
> Don't update to transformers 5.3.0.. The versions specified should work
> fine.  Just make sure you create from scratch in a conda env (Qwen3) -
> Conda envs are case sensitive.
> […](#)

It is an error. 
check model inputs exists in transformers 4.57.3 but not in 5.3.0. The Qwen TTS voice clone model works fine for me on 4.57.3 as it is the specified version but was hoping to somehow make it work with 5.3.0.

**Comment by kellyling80** [comment]
Wondering if anyone has managed to fix this ? getting the same pad_token_id error .
